version: '2'
 services:
   busybox:
     image: busybox
#   eureka:
#     image: andon/eureka:latest
#     expose:
#       - "8761"
#   customer:
#     image: customer:$GO_DEPENDENCY_LABEL_CUSTOMER_MASTER
#     expose:
#       - "8080"
#     links:
#      - eureka
#   catalog:
#     image: catalog:$GO_DEPENDENCY_LABEL_CATALOG_MASTER
#     expose:
#       - "8080"
#     links:
#      - eureka
#   order:
#     image: order:$GO_DEPENDENCY_LABEL_ORDER_MASTER
#     expose:
#       - "8080"
#     links:
#      - eureka
#   zuul:
#     image: zuul:$GO_DEPENDENCY_LABEL_ZUUL_MASTER
#     links:
#      - eureka
#     expose:
#       - "8080"
#   devicetunnel:
#     image: andon.artifactorypro.shared.pub.tds.tieto.com/andon-bitbar-tunnel:1.0.0
#   deviceproxy:
#     image: andon.artifactorypro.shared.pub.tds.tieto.com/andon-bitbar-proxy:1.0.0
