---
- hosts: localhost
  vars:
    - artifactory_url: "https://maven.etb.tieto.com/artifactory/andon/"
    - apikey: "{{ lookup('env'.'apikey') }}"
    - build_id: "{{lookup('env','build_id')}}"
    - apk_file: "com/tieto/andon/ecommerce/0.0.1-{{ build_id }}/ecommerce-0.0.1-{{ build_id }}.apk"
    - username: "{{lookup('env','username')}}"
    - passwd: "{{lookup('env','passwd')}}"
    - headers: "Accept: application/json"

  tasks:

  - name: Download the APK from Artifactory
    shell: curl -u{{ username }}:{{ passwd }} "{{ artifactory_url }}/{{ apk_file }}" -o /var/tmp/ecommerce-0.0.1-{{ build_id }}.apk

  - name: Upload APK to Bitbar cloud
    shell: curl -H "Accept: application/json" --user "{{ apikey }}:" -F myAppFile=@"/var/tmp/ecommerce-0.0.1-{{ build_id }}.apk" http://appium.testdroid.com/upload
    register: output
    failed_when: output.rc != 0

  - set_fact:
      session_id: "{{ output.stdout | from_json | json_query(id_query) }}"
    vars:
      id_query: "value.uploads.myAppFile"

  - debug: var=session_id

  - name: Write sessionid to file
    copy:
      content: session_id
      dest: /var/tmp/session.id
